version: '3'
services:
  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - "1880:1880/tcp"
    environment:
      - TZ=America/Chicago
    volumes:
      - ./data:/data
 #   depends_on:
 #     - homeassistant
 